[workspace]
members = [
    "crates/common", 
    "crates/mem-table",
    "crates/sst", "crates/storage",
    "crates/wal",
]

[package]
name = "lsm-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
wal = { path = "crates/wal" }
common = { path = "crates/common" }
sst = { path = "crates/sst" }
mem-table = { path = "crates/mem-table" }
storage = { path = "crates/storage" }
